services:
  satellite:
    build:
      context: .
      dockerfile: dockerfile.satellite
    devices:
      - /dev/snd:/dev/snd
    group_add:
      - audio
    ports:
      - "10700:10700"
    command:
      - "--name"
      - "AssistPi"
      - "--uri"
      - "tcp://0.0.0.0:10700"
      - "--mic-command"
      - "arecord -D plughw:CARD=seeed2micvoicec,DEV=0 -r 16000 -c 1 -f S16_LE -t raw"
      - "--snd-command"
      - "aplay -D plughw:CARD=seeed2micvoicec,DEV=0 -r 22050 -c 1 -f S16_LE -t raw"
      - "--wake-uri"
      - "tcp://wakeword:10400"
      - "--wake-word-name"
      - "ok_nabu"
      # Leds
      # - "--event-uri"
      # - "tcp://127.0.0.1:10500"
      - "--debug"
  wakeword:
    image: rhasspy/wyoming-openwakeword
    ports:
      - 10400:10400
