services:
  chown-fix:
    image: alpine:latest
    command: >
      sh -c "chown -R 1000:1000 /home/builder/buildroot/output /home/builder/buildroot/dl"
    volumes:
      # - ./output:/home/builder/buildroot/output
      - dl:/home/builder/buildroot/dl
    user: root
    restart: "no"

  buildroot:
    build: .
    container_name: buildroot-rpi0w2
    working_dir: /home/builder/buildroot
    stdin_open: true
    tty: true
    volumes:
      # - ./output:/home/builder/buildroot/output
      - dl:/home/builder/buildroot/dl
      - .:/repo
    command: ["/bin/bash"]
    environment:
      - BR2_EXTERNAL=/repo/packages
    depends_on:
      chown-fix:
        condition: service_completed_successfully

volumes:
  dl:
