x-base: &buildroot
  build: .
  working_dir: /home/builder/buildroot
  volumes:
    - dl:/home/builder/buildroot/dl
    - .:/repo
  environment:
    - BR2_EXTERNAL=/repo/external
  depends_on:
    chown-fix:
      condition: service_completed_successfully

services:
  chown-fix:
    image: alpine:latest
    command: >
      sh -c "chown -R 1000:1000 /home/builder/buildroot/dl"
    volumes:
      - dl:/home/builder/buildroot/dl
    user: root
    restart: "no"

  env:
    <<: *buildroot
    container_name: buildroot-env
    stdin_open: true
    tty: true
    command: ["/bin/bash"]
  
  build:
    <<: *buildroot
    container_name: buildroot-rpi0w2-rpi3
    command:
    - /bin/sh
    - -c
    - |
      make raspberrypi_3_zero2w_64_defconfig &&
      make && 
      cp output/images/sdcard.img.xz /repo/wyoming-satellite-rpi0w2-rpi3.img.xz


volumes:
  dl:
