FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

COPY dependencies.sh /tmp/dependencies.sh
RUN chmod +x /tmp/dependencies.sh && /tmp/dependencies.sh

RUN useradd -m -u 1000 -G sudo builder && \
    echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER builder
WORKDIR /home/builder

RUN git clone https://git.buildroot.net/buildroot && \
    cd buildroot && \
    git checkout 2025.08.x

WORKDIR /home/builder/buildroot

CMD ["/bin/bash"]
